sudo: false
language: python
python:
  - 2.7
install:
  - rm -rf ~/.nvm
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - makey setup

script:
  - makey travis-run

cache:
  directories:
  - "node_modules"

after_success:
  - makey send-coverage
